// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFXde2TW3AKhAYQMSnS3p_pBCdXS6MSI',
    appId: '1:110994836395:web:910edafe5a8d08f34360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    authDomain: 'dstorres-29bbe.firebaseapp.com',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    measurementId: 'G-ZJR46NFEWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1Z484lbCvx7sbIvUhFpT3En8ISUHSw4',
    appId: '1:110994836395:android:feb16590b957c4a64360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTsxGYAxKycAxuQ11ey5Yc3r4DSHUR2UQ',
    appId: '1:110994836395:ios:745f3a318b3fb8a84360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    androidClientId: '110994836395-78hrd07899tdjs349fb36k86go8egk3k.apps.googleusercontent.com',
    iosClientId: '110994836395-k7sllq0nh8i8dubokuo952cki3tadl01.apps.googleusercontent.com',
    iosBundleId: 'com.example.dstorresPlataforma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTsxGYAxKycAxuQ11ey5Yc3r4DSHUR2UQ',
    appId: '1:110994836395:ios:745f3a318b3fb8a84360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    androidClientId: '110994836395-78hrd07899tdjs349fb36k86go8egk3k.apps.googleusercontent.com',
    iosClientId: '110994836395-k7sllq0nh8i8dubokuo952cki3tadl01.apps.googleusercontent.com',
    iosBundleId: 'com.example.dstorresPlataforma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFXde2TW3AKhAYQMSnS3p_pBCdXS6MSI',
    appId: '1:110994836395:web:2f3f35712b7ccf484360ee',
    messagingSenderId: '110994836395',
    projectId: 'dstorres-29bbe',
    authDomain: 'dstorres-29bbe.firebaseapp.com',
    databaseURL: 'https://dstorres-29bbe-default-rtdb.firebaseio.com',
    storageBucket: 'dstorres-29bbe.appspot.com',
    measurementId: 'G-2FKDGZY40L',
  );
}
